version: '3.8'
services:
  mtquizbot-container:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/quizdb

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - ./sql/tables_init.sql:/docker-entrypoint-initdb.d/tables_init.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: