version: '3.8'
services:
  mtquizbot-container:
    image: client:0.0.1
    build:
      context: ./QuizBot
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/quiz_db_1
    networks:
      - postgres

  postgres:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: quiz_db_1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
    ports:
      - 5432
    volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

networks:
    postgres:
        driver: bridge
